server:
  port: 8084

spring:
  application:
    name: inss
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inss-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  messages:
    basename: i18n/message
    encoding: UTF-8

  flyway:
    baseline-on-migrate: true

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  database:
    driverClassName: org.postgresql.Driver

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db_inss
    username: postgres
    password: root
