server:
  port: 8081

spring:
  application:
    name: inss

  kafka:
    topic:
      inss-calculate: inss-calculate
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inss-group

  messages:
    basename: i18n/message
    encoding: UTF-8

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  database:
    driverClassName: org.postgresql.Driver

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db_inss
    username: postgres
    password: postgres

  flyway:
    baseline-on-migrate: true
